name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ci:
    name: test-ci
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10.20.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm --filter "./sdk-playground/packages/shared" build
      - run: pnpm --filter "./sdk-playground/packages/server" build
      - run: pnpm --filter "./sdk-playground/packages/client" build
      - run: pnpm lint
